import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../../src/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? 40 : 35,
    paddingBottom: 8,
    paddingHorizontal: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    height: 50,
    borderRadius: 25,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  filterButton: {
    padding: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 28,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
  },
  seeAllText: {
    fontSize: 14,
    fontWeight: '500',
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    marginVertical: 18,
  },
  emptyStateText: {
    fontSize: 16,
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 24,
  },
  createButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    marginVertical: 12,
  },
  loadingText: {
    fontSize: 16,
    marginTop: 12,
  },
  partnersContainer: {
    paddingRight: 16,
    paddingBottom: 10,
    marginBottom: 14,
  },
  partnerCard: {
    width: 130,
    borderRadius: 16,
    padding: 12,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    alignItems: 'center',
  },
  partnerAvatarContainer: {
    marginBottom: 8,
  },
  partnerAvatar: {
    width: 55,
    height: 55,
    borderRadius: 28,
  },
  partnerAvatarPlaceholder: {
    width: 55,
    height: 55,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  partnerAvatarText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  partnerName: {
    fontSize: 15,
    fontWeight: 'bold',
    marginBottom: 2,
    textAlign: 'center',
  },
  partnerDetail: {
    fontSize: 14,
    marginBottom: 2,
    textAlign: 'center',
  },
  partnerDistance: {
    fontSize: 13,
    marginBottom: 6,
    textAlign: 'center',
  },
  connectButton: {
    flexDirection: 'row',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  connectButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  eventsContainer: {
    paddingRight: 16,
    paddingBottom: 10,
    marginBottom: 14,
  },
  eventCard: {
    width: 200,
    borderRadius: 16,
    padding: 14,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  eventBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.accent,
  },
  eventBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 12,
  },
  eventDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  eventDetailIcon: {
    marginRight: 6,
  },
  eventDetailText: {
    fontSize: 13,
  },
  eventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  eventParticipants: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventParticipantsText: {
    fontSize: 12,
    marginLeft: 4,
  },
  eventCreator: {
    fontSize: 12,
  },
  facilitiesContainer: {
    paddingRight: 16,
    paddingBottom: 10,
  },
  facilityCard: {
    flexDirection: 'row',
    width: '100%',
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
    padding: 12,
  },
  facilityImageContainer: {
    width: '100%',
    height: 120,
  },
  facilityImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  facilityImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  facilityContent: {
    padding: 12,
  },
  facilityName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
  },
  facilityType: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  facilityAddress: {
    fontSize: 13,
    marginBottom: 4,
  },
  facilityDistance: {
    fontSize: 12,
    marginBottom: 4,
  },
  ratingContainer: {
    marginTop: 4,
  },
  allEventsContainer: {
    marginTop: 12,
    marginBottom: 12,
  },
  allEventsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  returnButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12, // Başlık ile arasında mesafe
    padding: 4,
  },
  sportFilterContainer: {
    paddingVertical: 4,
    marginBottom: 12,
    flexDirection: 'row',
  },
  sportFilterItem: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sportFilterItemActive: {
    borderWidth: 0,
  },
  sportFilterText: {
    fontSize: 12,
    fontWeight: '500',
  },
  verticalEventCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  verticalEventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sportBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.accent,
  },
  sportBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  verticalEventTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 12,
  },
  eventDistance: {
    fontSize: 10,
  },
  searchResultsContainer: {
    marginVertical: 8,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    marginBottom: 8,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  searchResultIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  searchResultTextContainer: {
    flex: 1,
  },
  searchResultTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  searchResultSubtitle: {
    fontSize: 13,
  },
  searchResultType: {
    fontSize: 12,
    fontWeight: '500',
  },
  dateFilterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 8,
    marginBottom: 12,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    borderRadius: 20,
  },
  dateFilterText: {
    fontSize: 14,
    fontWeight: '500',
  },
  filterBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0', // Default light color, will be overridden in component
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: {
    fontSize: 12,
    fontWeight: '500',
  },
  verticalFacilityCard: {
    width: '100%',
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
    flexDirection: 'row',
    padding: 12,
  },
  verticalFacilityImageContainer: {
    width: 100,
    height: 100,
    borderRadius: 10,
    overflow: 'hidden',
    marginRight: 12,
  },
  verticalFacilityImage: {
    width: '100%',
    height: 120,
    resizeMode: 'cover',
  },
  verticalFacilityContent: {
    padding: 12,
    flex: 1,
  },
  verticalFacilityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  verticalFacilityTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  facilityTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  facilityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: COLORS.accent,
  },
  facilityBadgeText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  facilityRating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  facilityRatingText: {
    marginLeft: 4,
    fontSize: 12,
    fontWeight: '600',
  },
  facilityDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  facilityDetailIcon: {
    marginRight: 6,
  },
  facilityDetailText: {
    fontSize: 13,
  },
  facilityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  verticalPartnerCard: {
    width: 240,
    borderRadius: 16,
    marginBottom: 12,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  verticalPartnerAvatarContainer: {
    width: 65,
    height: 65,
    borderRadius: 32.5,
    overflow: 'hidden',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  verticalPartnerAvatar: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  verticalPartnerContent: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 6,
  },
  verticalPartnerName: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  verticalPartnerDetail: {
    fontSize: 17,
    marginBottom: 4,
  },
  // "Tümünü Gör" sekmesinde görünen tam genişlik partner kartı
  fullWidthPartnerCard: {
    width: '100%',
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
});
