import { Event, Facility, Partner, SearchItem } from '../types/index';

// Arama için dummy veri
export const dummySearchData: SearchItem[] = [
  {
    id: 101,
    title: 'Halı Saha Maçı',
    type: 'Etkinlik',
    sportType: 'Futbol',
    location: 'Beşiktaş Halı Saha',
  },
  {
    id: 102,
    title: 'Basketbol Turnuvası',
    type: 'Etkinlik',
    sportType: 'Basketbol',
    location: 'Kadıköy Sahası',
  },
  {
    id: 103,
    title: 'Tenis Kulübü',
    type: 'Tesis',
    sportType: 'Tenis',
    location: 'Şişli Tenis Kortları',
  },
  { id: 104, title: 'Fitness Club', type: 'Tesis', sportType: 'Fitness', location: 'Beşiktaş' },
  {
    id: 105,
    title: 'Yüzme Antrenmanı',
    type: 'Etkinlik',
    sportType: 'Yüzme',
    location: 'Olimpik Havuz',
  },
];

// Yakındaki etkinlikler için dummy veriler
export const dummyEvents: Event[] = [
  {
    id: 1,
    title: 'Halı Saha Maçı',
    location: 'Beşiktaş Halı Saha',
    distance: '1.5 km',
    date: 'Yarın, 10:00',
    participants: '8/14',
    participantCount: 8,
    maxParticipants: 14,
    sportType: 'Futbol',
    creator: 'Ahmet Y.',
    creatorName: 'Ahmet Y.',
    creatorImage: '',
    time: '10:00',
    description:
      'Haftasonu eğlenceli bir maç yapmak için toplanıyoruz. Her seviyeden oyuncu katılabilir. Takımlar yerinde oluşturulacak. Katılım ücreti kişi başı 30 TL olup, maç sonrası içecekler dahildir.',
  },
  {
    id: 2,
    title: 'Basketbol Turnuvası',
    location: 'Kadıköy Basketbol Sahası',
    distance: '3.2 km',
    date: 'Cumartesi, 15:00',
    participants: '6/12',
    participantCount: 6,
    maxParticipants: 12,
    sportType: 'Basketbol',
    creator: 'Ayşe K.',
    creatorName: 'Ayşe K.',
    creatorImage: '',
    time: '15:00',
    description:
      'Sokak basketbolu etkinliğimize davetlisiniz. 3x3 formatında oynanacak, kazanan takıma küçük ödüller var. Başlangıç ve orta seviye oyuncular için uygundur.',
  },
  {
    id: 3,
    title: 'Tenis Etkinliği',
    location: 'İstanbul Tenis Kulübü',
    distance: '4.7 km',
    date: 'Pazar, 09:00',
    participants: '4/8',
    participantCount: 4,
    maxParticipants: 8,
    sportType: 'Tenis',
    creator: 'Mehmet D.',
    creatorName: 'Mehmet D.',
    creatorImage: '',
    time: '09:00',
    description:
      'Haftalık tenis buluşmamıza katılmak ister misiniz? Kort ücreti ortak karşılanacaktır. Raketinizi getirmeniz yeterlidir. Her seviyeden oyuncuyu bekliyoruz.',
  },
  {
    id: 4,
    title: 'Yüzme Buluşması',
    location: 'Olimpik Yüzme Havuzu',
    distance: '6.3 km',
    date: 'Pazartesi, 18:30',
    participants: '5/10',
    participantCount: 5,
    maxParticipants: 10,
    sportType: 'Yüzme',
    creator: 'Can A.',
    creatorName: 'Can A.',
    creatorImage: '',
    time: '18:30',
    description:
      'Havuzda grup halinde yüzme antrenmanı yapacağız. Temel yüzme teknikleri gösterilecek ve kondisyon çalışması yapılacaktır. Yüzme bonesi ve gözlüğünüzü getirmeyi unutmayın.',
  },
  {
    id: 5,
    title: 'Bisiklet Turu',
    location: 'Belgrad Ormanı',
    distance: '8.1 km',
    date: 'Çarşamba, 08:00',
    participants: '12/20',
    participantCount: 12,
    maxParticipants: 20,
    sportType: 'Bisiklet',
    creator: 'Zeynep T.',
    creatorName: 'Zeynep T.',
    creatorImage: '',
    time: '08:00',
    description:
      "Doğa içinde yaklaşık 25km'lik bir parkurda bisiklet süreceğiz. Orta zorlukta bir parkur olup, kendi bisikletinizi getirmeniz gerekmektedir. Kask takmak zorunludur.",
  },
];

// Yakındaki tesisler için dummy veri
export const dummyFacilities: Facility[] = [
  {
    id: '1',
    name: 'Fitness Club',
    type: 'Spor Salonu',
    sportType: 'Fitness',
    address: 'Beşiktaş, İstanbul',
    location: 'Beşiktaş, İstanbul',
    distance: '0.8 km',
    rating: 4.7,
    image: undefined,
    imageUrl: 'https://via.placeholder.com/200x120',
    openHours: '09:00-22:00',
  },
  {
    id: '2',
    name: 'Olimpik Yüzme Havuzu',
    type: 'Yüzme Tesisi',
    sportType: 'Yüzme',
    address: 'Kadıköy, İstanbul',
    location: 'Kadıköy, İstanbul',
    distance: '1.3 km',
    rating: 4.2,
    image: undefined,
    imageUrl: 'https://via.placeholder.com/200x120',
    openHours: '08:00-21:00',
  },
  {
    id: '3',
    name: 'Tenis Kortları',
    type: 'Tenis Kulübü',
    sportType: 'Tenis',
    address: 'Şişli, İstanbul',
    location: 'Şişli, İstanbul',
    distance: '2.5 km',
    rating: 4.5,
    image: undefined,
    imageUrl: 'https://via.placeholder.com/200x120',
    openHours: '08:00-20:00',
  },
  {
    id: '4',
    name: 'CrossFit Box',
    type: 'Spor Salonu',
    sportType: 'CrossFit',
    address: 'Etiler, İstanbul',
    location: 'Etiler, İstanbul',
    distance: '3.1 km',
    rating: 4.8,
    image: undefined,
    imageUrl: 'https://via.placeholder.com/200x120',
    openHours: '06:00-22:00',
  },
  {
    id: '5',
    name: 'Basketbol Sahası',
    type: 'Açık Alan Tesis',
    sportType: 'Basketbol',
    address: 'Levent, İstanbul',
    location: 'Levent, İstanbul',
    distance: '3.6 km',
    rating: 4.0,
    image: undefined,
    imageUrl: 'https://via.placeholder.com/200x120',
    openHours: '09:00-23:00',
  },
];

// Yakındaki spor arkadaşları için dummy veri
export const dummyPartners: Partner[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    age: 28,
    distance: '2.5 km',
    sport: 'Futbol',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/32.jpg',
    preferredSports: ['Futbol', 'Basketbol', 'Yüzme'],
  },
  {
    id: '2',
    name: 'Ayşe Kaya',
    age: 24,
    distance: '4 km',
    sport: 'Tenis',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/44.jpg',
    preferredSports: ['Tenis', 'Voleybol', 'Pilates'],
  },
  {
    id: '3',
    name: 'Mehmet Demir',
    age: 30,
    distance: '1.5 km',
    sport: 'Basketbol',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/22.jpg',
    preferredSports: ['Basketbol', 'Koşu'],
  },
  {
    id: '4',
    name: 'Zeynep Aydın',
    age: 26,
    distance: '3 km',
    sport: 'Yüzme',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/29.jpg',
    preferredSports: ['Yüzme', 'Yoga', 'Fitness'],
  },
  {
    id: '5',
    name: 'Burak Şahin',
    age: 32,
    distance: '5 km',
    sport: 'Koşu',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/36.jpg',
    preferredSports: ['Koşu', 'Futbol', 'Bisiklet'],
  },
  {
    id: '6',
    name: 'Elif Yıldız',
    age: 25,
    distance: '2 km',
    sport: 'Voleybol',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/2.jpg',
    preferredSports: ['Voleybol', 'Tenis', 'Yoga'],
  },
  {
    id: '7',
    name: 'Can Öztürk',
    age: 29,
    distance: '3.5 km',
    sport: 'Yüzme',
    avatar: 'https://randomuser.me/api/portraits/thumb/men/16.jpg',
    preferredSports: ['Yüzme', 'Fitness'],
  },
  {
    id: '8',
    name: 'Selin Korkmaz',
    age: 27,
    distance: '4.2 km',
    sport: 'Pilates',
    avatar: 'https://randomuser.me/api/portraits/thumb/women/17.jpg',
    preferredSports: ['Pilates', 'Yoga'],
  },
];
